global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics'  # /metrics endpoint'ini belirtiyoruz
    scheme: http             # Varsay覺lan olarak http, ancak https kullan覺yorsan覺z belirtin
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'  # Redis Exporter ile /metrics endpoint'ini kullan覺yoruz
